package com.redsamurai.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 22 09:56:33 EEST 2015
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    void filterByCountry(String countryId);
}

