package com.redsamurai.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 07 20:58:45 EET 2016
// ---------------------------------------------------------------------
public interface HrModule extends ApplicationModule {
    void testCall();
}

