package com.redsamurai.model.views;


import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 17 12:12:00 EEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
    }

    @Override
    protected ViewRowImpl createRowFromResultSet(Object object, ResultSet resultSet) {
        ViewRowImpl row = super.createRowFromResultSet(object, resultSet);
        return row;
    }
}

